### ISSUE TITLE
Parameter choices when some slices are missing regions at edges of slide

### ISSUE THREAD

**Issue by agelber-ucsd** [feiyoung/PRECAST#8]
Hi,

Thanks for this great tool! I had a question about parameter choice in a situation where I have many Visium slices but a third or so are missing some small (but important) region of the tissue, which causes the part to get clustered into the wrong cluster in the slices that do have it. I'm wondering if you have any suggestions for tuning some parameters to help this?

I was considering turning off the ICAR model, but would that still include v, just without the prior? I'm not sure what other parameters might help this, but I'd appreciate any suggestions.

-Alon

**Comment by feiyoung** [comment]
It is not a good choice to turn off the ICAR model, because it plays the key role to capture the batch effects among multiple slides. If turning off it, the component v will not be included in the model. If the batch effects in data are small, one can turn off it. There are many Visium slices for your data, thus, it is very likely to exists  batch effects.

There may be several reasons for the problem: (1) If the missing region is small, the number of clusters may not be sufficient for identifying the important small region. In this case, manually specifying a larger K could be tried. (2) If the region is small, it may be necessary to extract more information in the embedding space to identify the region. This can be done by increasing the number of factors (q, default q=15, see PRECAST(PRECASTObj, K=NULL, q= 15)). (3) Another option is to tune the initialization parameters int.model by revising the default value to int.model='EEE'. For DLPFC Visium data, significant improvements were observed by setting int.model='EEE'. (4) If none of the above work, the data could be divided into two groups, and PRECAST could be applied to each group separately.

We hope this information is helpful to you.
